import { useEffect, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { beginStudySession, completeStudySession, enrollStudy, getStudy, isConfigured, markStudyStarted, withdrawStudy } from "../../shared/api/api";

type Condition = "control" | "intervention";
export function StudyView({ remoteSession, onNotice }: { remoteSession: Session | null; onNotice: (message: string) => void }) {
  const [condition, setCondition] = useState<Condition | null>(null); const [enrolled, setEnrolled] = useState(false); const [before, setBefore] = useState(3); const [after, setAfter] = useState(3); const [sessionId, setSessionId] = useState<string | null>(null); const [started, setStarted] = useState(false);
  useEffect(() => { if (isConfigured && remoteSession) void getStudy(remoteSession).then((study) => { setEnrolled(Boolean(study.enrollment)); setCondition(study.condition); }).catch((error: Error) => onNotice(error.message)); }, [remoteSession, onNotice]);
  const enroll = async () => { if (!remoteSession) { setEnrolled(true); setCondition("control"); return; } const study = await enrollStudy(remoteSession); setEnrolled(true); setCondition(study.condition); };
  const begin = async () => { try { if (remoteSession && isConfigured) { const result = await beginStudySession(remoteSession, before); setSessionId(result.session.id); setCondition(result.session.condition); } else setSessionId("local-study-session"); setStarted(false); onNotice("Đã ghi nhận lúc bạn bị kẹt. Khi bạn bắt đầu, hãy bấm nút tiếp theo."); } catch (error) { onNotice(error instanceof Error ? error.message : "Không thể bắt đầu phiên pilot."); } };
  const markStart = async () => { try { if (remoteSession && isConfigured && sessionId) await markStudyStarted(remoteSession, sessionId); setStarted(true); onNotice("Đã ghi nhận hành động đầu tiên."); } catch (error) { onNotice(error instanceof Error ? error.message : "Không thể lưu mốc bắt đầu."); } };
  const finish = async (focusOutcome: "done" | "still_stuck" | "not_recorded") => { try { if (remoteSession && isConfigured && sessionId) await completeStudySession(remoteSession, sessionId, { frictionAfter: after, focusOutcome }); setSessionId(null); setStarted(false); onNotice("Cảm ơn bạn. Pilot chỉ lưu mốc thời gian và rating, không đọc nội dung task."); } catch (error) { onNotice(error instanceof Error ? error.message : "Không thể hoàn tất phiên pilot."); } };
  if (!enrolled) return <section className="feature-card"><p className="eyebrow">PILOT NGHIÊN CỨU</p><h1>Thử nghiệm Beneath the Pine trong 2 tuần.</h1><p>Bạn có thể rút lui bất kỳ lúc nào. Nghiên cứu chỉ dùng mốc thời gian, trạng thái và rating ma sát; không xuất nội dung task hoặc Brain Dump.</p><button className="primary" onClick={() => void enroll()}>Tôi đồng ý tham gia pilot</button></section>;
  return <><section className="page-intro"><p className="eyebrow">PILOT · {condition === "control" ? "LOGGER TỐI GIẢN" : "FULL BENEATH PINE"}</p><h1>{condition === "control" ? "Chỉ ghi nhận, chưa can thiệp." : "Dùng toàn bộ flow khi bạn bị kẹt."}</h1><p>Mỗi tuần hoàn thành ít nhất 3 phiên stuck → start.</p></section><section className="feature-card"><label>Ma sát trước khi bắt đầu: {before}/5<input type="range" min="1" max="5" value={before} onChange={(event) => setBefore(Number(event.target.value))} /></label>{!sessionId ? <button className="primary" onClick={() => void begin()}>Tôi đang bị kẹt</button> : <><button className="primary" disabled={started} onClick={() => void markStart()}>Tôi đã bắt đầu</button>{started && <><label>Ma sát sau phiên: {after}/5<input type="range" min="1" max="5" value={after} onChange={(event) => setAfter(Number(event.target.value))} /></label><div className="button-row"><button className="secondary" onClick={() => void finish("done")}>Đã xong</button><button className="secondary" onClick={() => void finish("still_stuck")}>Vẫn kẹt</button></div></>}</>}</section><section className="feature-card"><h2>Rút lui khỏi pilot</h2><p>Rút lui không ảnh hưởng đến tài khoản beta của bạn.</p><button className="danger" onClick={() => remoteSession && void withdrawStudy(remoteSession).then(() => { setEnrolled(false); setSessionId(null); })}>Rút lui</button></section></>;
}
