import { useEffect, useState } from "react";
import type { ReturnState } from "@beneath-the-pine/contracts";
import { deleteSeed, getReturnState, newRequestKey, startSolo, updateProfile } from "../../shared/api/api";
export function ReturnView({ onSession, onPact, onNotice }: { onSession: (id: string) => void; onPact: (id: string) => void; onNotice: (text: string) => void }) {
  const [state, setState] = useState<ReturnState | null>(null); const [intention, setIntention] = useState(""); const [duration, setDuration] = useState<5 | 10 | 25 | 50>(10); const [busy, setBusy] = useState(false);
  const load = () => void getReturnState().then(setState).catch(error => onNotice(error.message)); useEffect(load, []);
  if (!state) return <p role="status">Đang tìm điểm bạn đã dừng…</p>;
  if (!state.profileReady) return <section className="feature-card"><p className="eyebrow">BƯỚC ĐẦU TIÊN</p><h1>Giờ địa phương của bạn là gì?</h1><p>Thông tin này giúp Pine hiểu đúng lịch hẹn, không đoán từ vị trí.</p><button className="primary" onClick={() => void updateProfile({ timezone: Intl.DateTimeFormat().resolvedOptions().timeZone }).then(load)}>Dùng múi giờ thiết bị</button></section>;
  if (state.activeSession) return <section className="feature-card"><p className="eyebrow">PHIÊN ĐANG MỞ</p><h1>Bạn vẫn có thể quay lại.</h1><button className="primary" onClick={() => onSession(state.activeSession!.id)}>Vào lại phiên →</button></section>;
  return <><section className="page-intro"><p className="eyebrow">QUAY LẠI</p><h1>{state.openSeed ? "Lần trước bạn dừng ở đây." : "Một bước thôi, ngay lúc này."}</h1></section>{state.openSeed && <section className="feature-card"><blockquote>{state.openSeed.text}</blockquote><div className="button-row"><button className="primary" onClick={() => setIntention(state.openSeed!.text)}>Tiếp tục từ đây</button><button className="text-action" onClick={() => void deleteSeed().then(load)}>Bỏ điểm này</button></div></section>}<section className="feature-card"><label>Việc nhỏ bạn muốn bắt đầu<textarea value={intention} maxLength={280} onChange={event => setIntention(event.target.value)} /></label><label>Khoảng tập trung<select value={duration} onChange={event => setDuration(Number(event.target.value) as typeof duration)}>{[5,10,25,50].map(value => <option key={value} value={value}>{value} phút</option>)}</select></label><button className="primary" disabled={busy || !intention.trim()} onClick={() => { setBusy(true); void startSolo({ intention, durationMinutes: duration }, newRequestKey()).then(result => onSession(result.session.id)).catch(error => onNotice(error.message)).finally(() => setBusy(false)); }}>Bắt đầu yên lặng →</button></section>{state.upcomingPacts.length > 0 && <section className="feature-card"><h2>Focus Pact sắp tới</h2>{state.upcomingPacts.map(pact => <button className="text-action" key={pact.id} onClick={() => onPact(pact.id)}>{new Date(pact.startsAt).toLocaleString("vi-VN")} · {pact.durationMinutes} phút →</button>)}</section>}</>;
}
