import { useCallback, useRef, useState } from "react";
import { createCircleInvite, createPact, getCircle, getProfile, leaveCircle, newRequestKey, removeMember, revokeInvite, transferCircle, updateCircle } from "../../shared/api/api";
import { useResource } from "../../shared/api/useResource";
import { requestKeyStore } from "../../shared/api/requestKey";
import { Dialog, DurationPicker, ErrorMessage, type Duration } from "../../shared/components/ui";
import { deviceTimezone, formatTime, localToIso } from "../../shared/time";
export function CircleView({ id, accountId, onPact, onLeave }: { id: string; accountId: string; onPact: (id: string) => void; onLeave: () => void; onNotice: (text: string) => void }) {
  const loader = useCallback(async () => { const [group,profile] = await Promise.all([getCircle(id),getProfile()]); return { ...group,timezone:profile.profile?.timezone ?? deviceTimezone() }; },[id]);
  const resource = useResource(loader); const circle = resource.data?.circle;
  const [invite,setInvite] = useState<{id:string;token:string;expiresAt:string}|null>(null);
  const [selected,setSelected] = useState<string[]>([]); const [duration,setDuration] = useState<Duration>(25);
  const [scheduled,setScheduled] = useState(false); const [date,setDate] = useState(""); const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [message,setMessage] = useState("");
  const [rename,setRename] = useState(""); const [confirm,setConfirm] = useState<{title:string; action:()=>Promise<unknown>}|null>(null);
  const keys = useRef(requestKeyStore(newRequestKey)); const startTime = useRef<{signature:string;time:string}|null>(null);
  const act = async (action:()=>Promise<unknown>) => { if (busy) return; setBusy(true); setError(""); setMessage(""); try { await action(); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } };
  if (!circle) return <><ErrorMessage message={resource.error} retry={resource.reload}/>{resource.loading && <p role="status">Đang mở Circle…</p>}</>;
  const timezone = resource.data!.timezone;
  const candidates = circle.members?.filter(member => member.accountId !== accountId) ?? [];
  const owner = circle.myRole === "owner"; const archived = circle.status === "archived";
  const link = invite ? location.origin + location.pathname + "#invite/" + invite.token : "";
  return <><section className="page-intro"><p className="eyebrow">CIRCLE RIÊNG</p><h1>{circle.name}</h1><p>{circle.memberCount}/8 người · {owner ? "Bạn quản lý nhóm" : "Bạn là thành viên"}{archived ? " · Đã lưu trữ" : ""}</p></section><ErrorMessage message={error || resource.error} retry={resource.error ? resource.reload : undefined}/>{message && <p className="notice" role="status">{message}</p>}
    <section className="feature-card"><h2>Những người ở đây</h2><ul className="row-list">{circle.members?.map(member => <li key={member.accountId}><strong>{member.displayName ?? "Wanderer"}</strong>{member.accountId === accountId ? " · Bạn" : ""}{member.role === "owner" ? " · Chủ nhóm" : ""}{owner && member.accountId !== accountId && <div className="button-row"><button className="text-action" disabled={busy} onClick={() => setConfirm({ title:"Chuyển quyền quản lý cho " + (member.displayName ?? "thành viên này") + "?", action:async () => { await transferCircle(id,member.accountId); setInvite(null); await resource.reload(); } })}>Chuyển quyền</button><button className="text-action" disabled={busy} onClick={() => setConfirm({ title:"Bỏ " + (member.displayName ?? "thành viên này") + " khỏi nhóm?", action:async () => { await removeMember(id,member.accountId); setSelected(values => values.filter(value => value !== member.accountId)); await resource.reload(); } })}>Bỏ khỏi nhóm</button></div>}</li>)}</ul>{!owner && <button className="text-action" disabled={busy} onClick={() => setConfirm({ title:"Rời Circle " + circle.name + "?", action:async () => { await leaveCircle(id); onLeave(); } })}>Rời nhóm</button>}{owner && <p className="field-hint">Muốn rời nhóm? Chuyển quyền cho một thành viên trước.</p>}</section>
    {owner && <section className="feature-card"><h2>Chăm sóc khoảng chung</h2><form onSubmit={e => { e.preventDefault(); void act(async () => { await updateCircle(id,rename.trim()); await resource.reload(); setRename(""); setMessage("Đã đổi tên nhóm."); }); }}><label>Tên nhóm mới<input value={rename} maxLength={80} onChange={e => setRename(e.target.value)}/></label><button className="secondary" disabled={busy || !rename.trim()}>Lưu tên nhóm</button></form>{!archived && <><h3>Mời một người quen</h3><button className="secondary" disabled={busy || circle.memberCount >= 8} onClick={() => void act(async () => { setInvite((await createCircleInvite(id)).invite); })}>Tạo link mời 72 giờ</button>{invite && <div className="warm-card feature-card"><p className="invite-link">{link}</p><p className="field-hint">Hết hạn: {formatTime(invite.expiresAt,timezone)}. Link chỉ hiển thị trong lần mở này.</p><div className="button-row"><button className="secondary" onClick={() => void act(async () => { await navigator.clipboard.writeText(link); setMessage("Đã sao chép link mời."); })}>Sao chép link</button><button className="text-action" disabled={busy} onClick={() => setConfirm({ title:"Thu hồi link mời vừa tạo?", action:async () => { await revokeInvite(id,invite.id); setInvite(null); } })}>Thu hồi</button></div></div>}</>}</section>}
    {!archived && <form className="feature-card narrow-content" onSubmit={e => { e.preventDefault(); void act(async () => {
      const signature = JSON.stringify({selected,duration,scheduled,date});
      if (startTime.current?.signature !== signature) startTime.current = { signature,time:scheduled ? localToIso(date,timezone) ?? "" : new Date().toISOString() };
      if (!startTime.current.time) throw new Error("Ngày giờ chưa hợp lệ trong múi giờ đã chọn.");
      const payload = { participantIds:selected,startsAt:startTime.current.time,durationMinutes:duration };
      const result = await createPact(id,payload,keys.current.for(payload)); onPact(result.pact.id);
    }); }}><p className="eyebrow">FOCUS PACT</p><h2>Hẹn một chặng cùng nhau.</h2><p>Mỗi người làm việc của riêng mình. Chọn từ 1 đến 7 người quen.</p>{candidates.length ? candidates.map(member => <label className="check-label" key={member.accountId}><input type="checkbox" checked={selected.includes(member.accountId)} onChange={e => setSelected(values => e.target.checked ? [...values,member.accountId] : values.filter(value => value !== member.accountId))}/>{member.displayName ?? "Wanderer"}</label>) : <p className="field-hint">Mời thêm một người để tạo Pact.</p>}<DurationPicker value={duration} onChange={setDuration}/><label>Thời điểm<select value={scheduled ? "later" : "now"} onChange={e => setScheduled(e.target.value === "later")}><option value="now">Bắt đầu ngay</option><option value="later">Đặt lịch</option></select></label>{scheduled && <label>Ngày và giờ ({timezone})<input type="datetime-local" required value={date} onChange={e => setDate(e.target.value)}/></label>}<button className="primary" disabled={busy || !selected.length || (scheduled && !date)}>{busy ? "Đang tạo cuộc hẹn…" : "Tạo Focus Pact"}</button><p className="field-hint">Sau khi tạo, chia sẻ link Pact cho những người được chọn.</p></form>}
    {confirm && <Dialog title={confirm.title} onClose={() => { if (!busy) setConfirm(null); }}><p>Thao tác áp dụng cho Circle “{circle.name}”.</p><ErrorMessage message={error}/><button className="danger" disabled={busy} onClick={() => void act(async () => { await confirm.action(); setConfirm(null); })}>{busy ? "Đang xử lý…" : "Xác nhận"}</button></Dialog>}
  </>;
}
