import { PactsView } from "../pacts/PactsView";
import { InviteList } from "./InviteList";
import "./circles.css";
import { usePrivateDraft } from "../../shared/auth/usePrivateDraft";
import { useCallback, useEffect, useRef, useState } from "react";
import { setCircleStatus, ApiRequestError, createCircleInvite, createPact, getCircle, getProfile, leaveCircle, newRequestKey, removeMember, revokeInvite, transferCircle, updateCircle } from "../../shared/api/api";
import { useResource } from "../../shared/api/useResource";
import { requestKeyStore } from "../../shared/api/requestKey";
import { Dialog, DurationPicker, ErrorMessage, type Duration } from "../../shared/components/ui";
import { deviceTimezone, formatTime, localToIso } from "../../shared/time";
export function CircleView({ id, accountId, onPact, onLeave }: { id: string; accountId: string; onPact: (id: string) => void; onLeave: () => void; onNotice: (text: string) => void }) {
  const loader = useCallback(async () => { const [group,profile] = await Promise.all([getCircle(id),getProfile()]); return { ...group,timezone:profile.profile?.timezone ?? deviceTimezone() }; },[id]);
  const resource = useResource(loader); const circle = resource.data?.circle;
  const [copyMessage,setCopyMessage] = useState(""); const [copyError,setCopyError] = useState("");
  const [inviteRevision,setInviteRevision] = useState(0);
  const [invite,setInvite] = useState<{id:string;token:string;expiresAt:string}|null>(null);
  const [selected,setSelected,clearSelected] = usePrivateDraft<string[]>(`circle:${id}:selected`,[]); const [duration,setDuration,clearDuration] = usePrivateDraft<Duration>(`circle:${id}:duration`,25);
  const [scheduled,setScheduled,clearScheduled] = usePrivateDraft(`circle:${id}:scheduled`,false); const [date,setDate,clearDate] = usePrivateDraft(`circle:${id}:date`,""); const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [message,setMessage] = useState("");
  const [rename,setRename] = useState(""); const [confirm,setConfirm] = useState<{title:string; description?:string; action:()=>Promise<unknown>}|null>(null);
  const [retry] = usePrivateDraft(`circle:${id}:retry`, () => ({ keys:requestKeyStore(newRequestKey), start:null as {signature:string;time:string}|null }));
  const pending = useRef(false); const [errorArea,setErrorArea] = useState("manage");
  const [selectionNotice,setSelectionNotice] = useState("");
  useEffect(() => { if (!circle) return; const valid = selected.filter(value => value !== accountId && circle.members?.some(member => member.accountId === value)); if (valid.length !== selected.length) { setSelected(valid); setSelectionNotice("Danh sách thành viên đã thay đổi. Hãy kiểm tra lại người được mời."); } if (circle.myRole !== "owner") setInvite(null); }, [circle,accountId,selected,setSelected]);
  const act = async (action:()=>Promise<unknown>, area = "manage") => { if (pending.current) return; pending.current = true; setErrorArea(area); setBusy(true); setError(""); setMessage(""); try { await action(); } catch(e) { setError((e as Error).message); if (e instanceof ApiRequestError && [403,404,409].includes(e.status ?? 0)) { if (e.status !== 409) resource.setData(null); await resource.reload(); } } finally { pending.current = false; setBusy(false); } };
  if (!circle) return <><ErrorMessage message={resource.error} retry={resource.reload}/>{resource.loading && <p role="status">Đang mở Circle…</p>}</>;
  const timezone = resource.data!.timezone;
  const candidates = circle.members?.filter(member => member.accountId !== accountId) ?? [];
  const owner = circle.myRole === "owner"; const archived = circle.status === "archived";
  const link = invite ? location.origin + location.pathname + "#invite/" + invite.token : "";
  return <div className="circles-page circle-detail"><section className="page-intro"><p className="eyebrow">CIRCLE RIÊNG</p><h1>{circle.name}</h1><p>{circle.memberCount}/8 người · {owner ? "Bạn quản lý nhóm" : "Bạn là thành viên"}{archived ? " · Đã lưu trữ" : ""}</p></section><ErrorMessage message={resource.error} retry={resource.reload}/>{message && <p className="notice" role="status">{message}</p>}
    {!archived && <form className="circle-panel pact-composer" onSubmit={e => { e.preventDefault(); void act(async () => {
      const signature = JSON.stringify({selected,duration,scheduled,date,timezone});
      if (retry.start?.signature !== signature) retry.start = { signature,time:scheduled ? localToIso(date,timezone) ?? "" : new Date().toISOString() };
      if (!retry.start.time) throw new Error("Ngày giờ chưa hợp lệ trong múi giờ đã chọn.");
      const payload = { participantIds:selected,startsAt:retry.start.time,durationMinutes:duration };
      const result = await createPact(id,payload,retry.keys.for(payload)); clearSelected(); clearDuration(); clearScheduled(); clearDate(); retry.keys.clear(); retry.start = null; onPact(result.pact.id);
    }, "pact"); }}><fieldset disabled={busy}><p className="eyebrow">FOCUS PACT</p><h2>Hẹn một chặng cùng nhau.</h2><p>Mỗi người làm việc của riêng mình. Chọn từ 1 đến 7 người quen.</p><h3>Hẹn với ai?</h3><p role="status" className="field-hint">Đã chọn {selected.length}/7 người. {selectionNotice}</p>{candidates.length ? candidates.map(member => <label className="check-label" key={member.accountId}><input type="checkbox" checked={selected.includes(member.accountId)} onChange={e => setSelected(values => e.target.checked ? [...values,member.accountId] : values.filter(value => value !== member.accountId))}/>{member.displayName ?? "Wanderer"}</label>) : <p className="field-hint">Mời thêm một người để tạo Pact.</p>}<DurationPicker value={duration} onChange={setDuration}/><label>Thời điểm<select value={scheduled ? "later" : "now"} onChange={e => setScheduled(e.target.value === "later")}><option value="now">Hẹn ngay bây giờ</option><option value="later">Đặt lịch</option></select></label>{scheduled && <label>Ngày và giờ ({timezone})<input type="datetime-local" required value={date} onChange={e => setDate(e.target.value)}/></label>}<p className="field-hint">Mời {selected.length} người · {duration} phút · {scheduled ? (date ? `${date.replace("T"," ")} (${timezone})` : "Chưa chọn giờ") : "Hẹn ngay bây giờ"}</p><ErrorMessage message={errorArea === "pact" ? error : ""}/><button className="primary" disabled={busy || !selected.length || (scheduled && !date)}>{busy ? "Đang tạo cuộc hẹn…" : "Tạo Focus Pact"}</button><p className="field-hint">Sau khi tạo, chia sẻ link Pact cho những người được chọn. Phiên chỉ chạy khi người tạo bắt đầu Pact.</p></fieldset></form>}
    <section className="circle-members"><ErrorMessage message={errorArea === "manage" && !owner && !confirm ? error : ""}/><h2>Những người ở đây</h2><ul className="row-list">{circle.members?.map(member => <li key={member.accountId}><strong>{member.displayName ?? "Wanderer"}</strong>{member.accountId === accountId ? " · Bạn" : ""}{member.role === "owner" ? " · Chủ nhóm" : ""}{owner && member.accountId !== accountId && <details><summary>Quản lý thành viên</summary><div className="button-row"><button className="text-action" disabled={busy} onClick={() => setConfirm({ title:"Chuyển quyền quản lý cho " + (member.displayName ?? "thành viên này") + "?", action:async () => { await transferCircle(id,member.accountId); setInvite(null); await resource.reload(); } })}>Chuyển quyền</button><button className="text-action" disabled={busy} onClick={() => setConfirm({ title:"Bỏ " + (member.displayName ?? "thành viên này") + " khỏi nhóm?", action:async () => { await removeMember(id,member.accountId); setSelected(values => values.filter(value => value !== member.accountId)); await resource.reload(); } })}>Bỏ khỏi nhóm</button></div></details>}</li>)}</ul>{!owner && <button className="text-action" disabled={busy} onClick={() => setConfirm({ title:"Rời Circle " + circle.name + "?", action:async () => { await leaveCircle(id); onLeave(); } })}>Rời nhóm</button>}{owner && <p className="field-hint">Muốn rời nhóm? Chuyển quyền cho một thành viên trước.</p>}</section>
    {owner && <details className="circle-management"><summary>Quản lý nhóm và lời mời</summary><ErrorMessage message={errorArea === "manage" && !confirm ? error : ""}/><form onSubmit={e => { e.preventDefault(); void act(async () => { await updateCircle(id,rename.trim()); await resource.reload(); setRename(""); setMessage("Đã đổi tên nhóm."); }); }}><label>Tên nhóm mới<input disabled={busy} value={rename} maxLength={80} onChange={e => setRename(e.target.value)}/></label><button className="secondary" disabled={busy || !rename.trim()}>Lưu tên nhóm</button></form>{!archived && <><h3>Mời một người quen</h3><button className="secondary" disabled={busy || circle.memberCount >= 8} onClick={() => void act(async () => { setInvite((await createCircleInvite(id)).invite); setInviteRevision(value=>value+1); })}>Tạo link mời 72 giờ</button>{circle.memberCount >= 8 && <p className="field-hint">Circle đã đủ 8 người.</p>}{invite && <div className="circle-invite"><ErrorMessage message={copyError}/>{copyMessage && <p role="status">{copyMessage}</p>}<p className="invite-link">{link}</p><p className="field-hint">Hết hạn: {formatTime(invite.expiresAt,timezone)}. Link chỉ hiển thị trong lần mở này.</p><div className="button-row"><button className="secondary" disabled={busy} onClick={() => { setCopyError(""); setCopyMessage(""); void navigator.clipboard.writeText(link).then(() => setCopyMessage("Đã sao chép link mời.")).catch(() => setCopyError("Chưa sao chép được. Bạn có thể chọn và sao chép link bên dưới.")); }}>Sao chép link</button><button className="text-action" disabled={busy} onClick={() => setConfirm({ title:"Thu hồi link mời vừa tạo?", action:async () => { await revokeInvite(id,invite.id); setInvite(null); setInviteRevision(value=>value+1); } })}>Thu hồi</button></div></div>}</>}<InviteList id={id} timezone={timezone} revision={inviteRevision} onRevoked={revoked=>{if(invite?.id===revoked)setInvite(null);}}/><button className="secondary" disabled={busy} onClick={()=>setConfirm({title:archived ? "Khôi phục Circle này?" : "Lưu trữ Circle này?",description:archived ? "Nhóm sẽ nhận cuộc hẹn và lời mời mới. Link đã thu hồi vẫn không sử dụng được." : "Chỉ lưu trữ khi không còn cuộc hẹn mở. Các lời mời chưa dùng sẽ bị thu hồi và nhóm tạm ngừng nhận cuộc hẹn mới.",action:async()=>{try{await setCircleStatus(id,archived?'active':'archived');}catch(failure){if(failure instanceof ApiRequestError && failure.status===409) throw new Error("Nhóm còn cuộc hẹn chưa khép lại. Hãy xử lý các cuộc hẹn trước khi lưu trữ.");throw failure;}setInvite(null);setInviteRevision(value=>value+1);await resource.reload();}})}>{archived ? "Khôi phục Circle" : "Lưu trữ Circle"}</button><p className="field-hint">Lưu trữ chỉ thực hiện khi không còn cuộc hẹn mở. Các lời mời chưa dùng sẽ bị thu hồi; khôi phục không làm link cũ hoạt động lại.</p></details>}
    <div className="circle-pacts"><PactsView circleId={id} onOpen={onPact}/></div>
    {confirm && <Dialog title={confirm.title} onClose={() => { if (!busy) setConfirm(null); }}><p>{confirm.description ?? `Thao tác áp dụng cho Circle “${circle.name}”.`}</p><ErrorMessage message={error}/><button className="danger" disabled={busy} onClick={() => void act(async () => { await confirm.action(); setConfirm(null); })}>{busy ? "Đang xử lý…" : "Xác nhận"}</button></Dialog>}
  </div>;
}
